export const COLUMN_SYNONYMS = {
  DATE: [
    'date',
    'txn date',
    'transaction date',
    'value date',
    'posting date',
    'trans date',
    'tran date',
    'booking date',
    'txndate',
    'transdate',
    'value_date',
    'post_date',
    'date of transaction',
    'statement date',
  ],
  DESCRIPTION: [
    'description',
    'narration',
    'particulars',
    'details',
    'transaction details',
    'remarks',
    'transaction description',
    'narrative',
    'payee',
    'merchant',
    'transaction remarks',
    'counterparty',
    'memo',
    'trans description',
    'desc',
    'info',
    'transaction particulars',
  ],
  TYPE: [
    'type',
    'txn type',
    'transaction type',
    'cr/dr',
    'dr/cr',
    'd/c',
    'c/d',
    'credit/debit',
    'debit/credit',
    'indicator',
    'entry type',
    'trx type',
    'cr / dr',
    'dr / cr',
  ],
  DEBIT: [
    'debit',
    'debit amount',
    'withdrawal',
    'withdrawal amt',
    'withdrawal amount',
    'withdrawals',
    'dr',
    'dr amount',
    'dr amt',
    'paid out',
    'spent',
    'money out',
    'debit (inr)',
    'debit amount (inr)',
    'withdrawal (inr)',
    'withdrawal (dr)',
    'debit (dr)',
    'withdrawal amount (inr)',
    'debit (usd)',
    'debit (eur)',
    'dr (inr)',
  ],
  CREDIT: [
    'credit',
    'credit amount',
    'deposit',
    'deposit amt',
    'deposit amount',
    'deposits',
    'cr',
    'cr amount',
    'cr amt',
    'paid in',
    'received',
    'money in',
    'credit (inr)',
    'credit amount (inr)',
    'deposit (inr)',
    'deposit (cr)',
    'credit (cr)',
    'deposit amount (inr)',
    'credit (usd)',
    'credit (eur)',
    'cr (inr)',
  ],
  AMOUNT: [
    'amount',
    'txn amount',
    'transaction amount',
    'net amount',
    'amount (inr)',
    'amount (usd)',
    'amount (eur)',
    'trans amount',
    'sum',
    'txn amt',
  ],
  BALANCE: [
    'balance',
    'closing balance',
    'available balance',
    'running balance',
    'bal',
    'bal (inr)',
    'balance (inr)',
    'account balance',
    'net balance',
    'closing bal',
  ],
  REFERENCE: [
    'reference',
    'ref no',
    'ref number',
    'transaction id',
    'utr',
    'cheque number',
    'chq no',
    'chq/ref no',
    'ref/chq no',
    'ref#',
    'txn id',
    'utr number',
    'reference no',
    'ref/utr',
    'chq / ref no',
  ],
};
